export enum EnviromentVariablesEnum {
    PORT = 'PORT',
    ENABLE_CORS = 'ENABLE_CORS',
    JWT_KEY = 'JWT_KEY',
    JWT_EXPIRATION = 'JWT_EXPIRATION',
    NOSQL_CONNECTION_STRING = 'NOSQL_CONNECTION_STRING',
}